### PR TITLE
Fixes issues related to matrix positioning

### PR DESCRIPTION
**Pull request by onursehitoglu**

### CODE REVIEW

**Comment by dudebout** [comment]
Thank you very much @onursehitoglu for this PR. To check its effect I [crafted an example](https://github.com/dudebout/matrix.skeleton/commit/0d93d24a8d9f16956d78ccc32c30ec3e8072e93f) that I intend to leave as a sort of regression test. Here is what it looks like with code on master:

result-master

Here is what it looks like with your fix:

result-pr

You are definitely on the right track! The skeletons are in the right place if all the columns on the last row are the same size. However, if the first non-empty node in the last row is not the tallest, the skeleton for that matrix is placed a bit too low.

I found this corner case while studying your code. I was curious about the `\breakforeach` instruction, and the comment
```
% find any node in the last row and set \ck@shift@y to difference between text and south anchors
```
It was not clear how we could construct the correct skeleton if we do not consider all the nodes in the last row.

I wonder if we could compute the minimum `y` displacement over all the columns in the last row to get the correct positioning.

**Comment by onursehitoglu** [comment]
Hi,
  I hit the same problem. Also it was not working for labeled nodes ` |(foo)| first & |(bar)| second \\` . 
I pushed a solution to master branch https://github.com/onursehitoglu/matrix.skeleton . 

This one finds the maximum displacement in last row and uses it. It works for the example above and other examples I have. 
It still has an issue. If anchor of a last row cell is changed to something other than,`base, base west, base east, text` it miscalculates the offset. I could not find a way to get the anchor of a pgf node. Sample issue: (second row second column of matrix A)
```latex
\begin{tikzpicture}

\tikzset{my-matrix/.style={matrix of math nodes, label skeleton,
                           left delimiter=(, right delimiter =)}}

\matrix (A) [my-matrix] {
  a_{11} & a_{12} \\
  a_{21} & |[anchor=north]| \frac{1}{a'_{22}} \\
};
\matrix (C) [my-matrix, right= of A] {
  a_{11} \cdot b_1 + a_{12} \cdot b_2 \\
  a_{21} \cdot b_1 + a_{22} \cdot b_2 \\
};
\matrix (B) [my-matrix, above=of C] {
  b_1 \\
  b_2 \\
};

\fitandstyle{(A-row-1)}{draw=red, fill=red!25, opacity=0.5}
\fitandstyle{(A-row-2)}{draw=blue, fill=blue!25, opacity=0.5}
\fitandstyle{(B-column-1)}{draw=yellow, fill=yellow!25, opacity=0.5}
\fitandstyle{(C-cell-1-1)}{draw=orange, fill=orange!25, opacity=0.5}
\fitandstyle{(C-cell-2-1)}{draw=green, fill=green!25, opacity=0.5}

\end{tikzpicture}
```
I believe it is still usable.

**Comment by dudebout** [comment]
Thank you for the quick fix. Unfortunately, I believe the change of anchor would be a regression. In the single-matrix case, I believe the existing code can handle any anchor, but the new code would not work with some of them.

I'm thinking of setting up a document called `regression.tex` to capture a number of these corner cases to make sure we don't break something while trying to improve something else. I tried for a few minutes to find a way to find the anchor of a given node instead of passing `base` in the diff but was not able to.

**Comment by onursehitoglu** [comment]
I believe this time it works. Solution is much more simpler. Using `\pgf@matrix@miny\pgfmatrixcurrentrow` is sufficient. I tried this before but ignored `\pgfmatrixrowsep`. Combining both gives us the working offset from matrix south anchor.

**Comment by dudebout** [comment]
Thanks a lot for this PR @onursehitoglu. I have merged it, along with a first stab at a collection of regression tests for this package.

**Pull request closed without merging**
